apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recipe-app
  template:
    metadata:
      labels:
        app: recipe-app
    spec:
      containers:
        - name: recipe-app
          image: recipe-app:latest
          imagePullPolicy: Never   # <-- THIS IS REQUIRED
          ports:
            - containerPort: 80
